/**
 * Kysely types of the table the `customers` module owns (EVM-020). `platform` does not know module tables: the module narrows a
 * handle with `db.$extendTables<CustomerTables>()`. The application role has SELECT, INSERT and UPDATE (no DELETE: soft delete
 * only). `display_name`, `sort_name` and `search_text` are generated by the database — they can be read, never written.
 */
import type { Generated, GeneratedAlways, Kysely } from 'kysely';
import type { Database } from '../../../platform/database/database.ts';
import type { CustomerKind } from '../domain/customer.ts';

export interface CustomersTable {
  id: string;
  kind: CustomerKind;
  first_name: string | null;
  last_name: string | null;
  company_name: string | null;
  tax_id: string | null;
  contact_person_name: string | null;
  phone: string;
  email: string | null;
  street: string | null;
  building_number: string | null;
  apartment_number: string | null;
  postal_code: string | null;
  city: string | null;
  notes: string | null;
  display_name: GeneratedAlways<string>;
  sort_name: GeneratedAlways<string>;
  search_text: GeneratedAlways<string>;
  created_at: Date;
  created_by: string | null;
  updated_at: Date;
  updated_by: string | null;
  version: Generated<number>;
  deleted_at: Date | null;
  deleted_by: string | null;
}

export type CustomerTables = { 'customers.customers': CustomersTable };

export type CustomersDb = Kysely<CustomerTables>;

export const customerTables = (db: Kysely<Database>): CustomersDb => db.$extendTables<CustomerTables>();
