/**
 * Icons of the panel (Lucide, ISC — styleguide § 2.10). Applications import icons only from @evia/ui-web, so the
 * set stays consistent with the styleguide's icon dictionary (dependency-cruiser: apps/web does not import lucide-react).
 */
export {
  AlarmClock,
  Ban,
  Banknote,
  Calculator,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  ClipboardList,
  EllipsisVertical,
  Hourglass,
  Inbox,
  Info,
  KeyRound,
  Link2Off,
  LoaderCircle,
  Lock,
  Menu,
  OctagonAlert,
  Search,
  Shield,
  ShieldCheck,
  SearchX,
  ShieldX,
  ThumbsUp,
  TriangleAlert,
  Users,
  WifiOff,
  Wrench,
  X,
} from 'lucide-react';
export type { LucideIcon as Icon } from 'lucide-react';
