/**
 * Build of design tokens with Style Dictionary 5 (ADR-0006, EVM-006 AC6).
 * Style Dictionary parses the merged W3C DTCG tree and resolves aliases; our formats convert the resolved values
 * (src/transform.ts) and export only non-deprecated semantic tokens:
 *   dist/web/tokens.css     — `:root` with `--evm-…` custom properties (light theme)
 *   dist/web/tailwind-theme.css — Tailwind CSS 4 `@theme` with the layout tokens (breakpoints, grid margins and gutters)
 *                             from base/breakpoints.tokens.json: they have no semantic layer (styleguide § 2.4) and media
 *                             queries need literal values (ADR-0006; EVM-008)
 *   dist/mobile/tokens.js   — frozen ESM constants for React Native, one named export per top-level group
 *   dist/mobile/tokens.d.ts — literal, readonly types of those constants
 * Output names do not depend on the theme: a dark theme will be an addition, not an API change (W4).
 */
import { mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import StyleDictionary from 'style-dictionary';
import type { DesignTokens, Dictionary, TransformedToken } from 'style-dictionary/types';
import { collectTokens, loadTokenFiles, type TokenFile, validateTokens } from './model.ts';
import { cssDeclarations, mobileKey, mobileValue, type TokenInput } from './transform.ts';

export class TokenValidationError extends Error {
  readonly errors: readonly string[];

  constructor(errors: readonly string[]) {
    super(`design tokens are invalid:\n${errors.join('\n')}`);
    this.name = 'TokenValidationError';
    this.errors = errors;
  }
}

const HEADER = [
  '/**',
  ' * Generated by @evia/tokens from design/tokens (W3C DTCG) — do not edit.',
  ' * Rules of use: docs/ux/styleguide.md; only semantic tokens are exported.',
  ' */',
].join('\n');

export const OUTPUTS = ['web/tokens.css', 'web/tailwind-theme.css', 'mobile/tokens.js', 'mobile/tokens.d.ts'] as const;

const THEME_HEADER = [
  '/**',
  ' * Generated by @evia/tokens from design/tokens (W3C DTCG) — do not edit.',
  ' * Tailwind CSS 4 theme of the layout tokens (breakpoint.*, grid.*.margin, grid.*.gutter): styleguide § 2.4.',
  ' */',
].join('\n');

/** Layout tokens exported to the Tailwind theme: breakpoints and grid dimensions (not column counts). */
const isLayoutToken = (token: TransformedToken): boolean =>
  (token.path[0] === 'breakpoint' || token.path[0] === 'grid') && token.$type === 'dimension';

type Tree = Record<string, unknown>;

const isTree = (value: unknown): value is Tree => typeof value === 'object' && value !== null && !Array.isArray(value);

/** Deep merge of token files; validation guarantees that no token path is defined twice. */
function merge(target: Tree, source: Tree): Tree {
  for (const [key, value] of Object.entries(source)) {
    const existing = target[key];
    target[key] = isTree(existing) && isTree(value) ? merge({ ...existing }, value) : value;
  }
  return target;
}

/** Validates the tokens and writes the outputs; returns the repository-independent output paths (relative to outDir). */
export async function buildTokens({ sourceDir, outDir }: { sourceDir: string; outDir: string }): Promise<readonly string[]> {
  const files: TokenFile[] = loadTokenFiles(sourceDir);
  if (files.length === 0) throw new Error(`no *.tokens.json files in ${join(sourceDir, 'base')} or ${join(sourceDir, 'semantic')}`);
  const { tokens, errors } = collectTokens(files);
  const problems = [...errors, ...validateTokens(tokens)];
  if (problems.length > 0) throw new TokenValidationError(problems);

  const exportedPaths = new Set(
    [...tokens.values()].filter((token) => token.layer === 'semantic' && !token.deprecated).map((token) => token.path),
  );
  const exported = (token: TransformedToken): boolean => exportedPaths.has(token.path.join('.'));
  const input = (token: TransformedToken): TokenInput => ({
    path: token.path,
    type: String(token.$type),
    value: token.$value,
    extensions: token.$extensions as TokenInput['extensions'],
  });

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  const sd = new StyleDictionary({
    tokens: files.reduce<Tree>((tree, file) => merge(tree, file.data as Tree), {}) as DesignTokens,
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    hooks: {
      filters: { 'evm/exported': exported, 'evm/layout': isLayoutToken },
      formats: {
        'evm/web/css': ({ dictionary }: { dictionary: Dictionary }) => webCss(dictionary.allTokens.map(input)),
        'evm/web/tailwind-theme': ({ dictionary }: { dictionary: Dictionary }) => tailwindTheme(dictionary.allTokens.map(input)),
        'evm/mobile/js': ({ dictionary }: { dictionary: Dictionary }) => mobileJs(groups(dictionary.allTokens.map(input))),
        'evm/mobile/dts': ({ dictionary }: { dictionary: Dictionary }) => mobileDts(groups(dictionary.allTokens.map(input))),
      },
    },
    platforms: {
      web: {
        transforms: [],
        buildPath: `${join(outDir, 'web')}/`,
        files: [
          { destination: 'tokens.css', format: 'evm/web/css', filter: 'evm/exported' },
          { destination: 'tailwind-theme.css', format: 'evm/web/tailwind-theme', filter: 'evm/layout' },
        ],
      },
      mobile: {
        transforms: [],
        buildPath: `${join(outDir, 'mobile')}/`,
        files: [
          { destination: 'tokens.js', format: 'evm/mobile/js', filter: 'evm/exported' },
          { destination: 'tokens.d.ts', format: 'evm/mobile/dts', filter: 'evm/exported' },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
  return OUTPUTS;
}

function webCss(tokens: readonly TokenInput[]): string {
  const lines = tokens.flatMap((token) => cssDeclarations(token).map(([name, value]) => `  ${name}: ${value};`));
  return `${HEADER}\n:root {\n${lines.join('\n')}\n}\n`;
}

/** `--evm-breakpoint-*` → `--breakpoint-*` (Tailwind variants), `--evm-grid-*` → `--spacing-grid-*` (spacing utilities). */
function tailwindTheme(tokens: readonly TokenInput[]): string {
  const lines = tokens.flatMap((token) =>
    cssDeclarations(token).map(
      ([name, value]) => `  ${name.replace(/^--evm-breakpoint-/, '--breakpoint-').replace(/^--evm-grid-/, '--spacing-grid-')}: ${value};`,
    ),
  );
  return `${THEME_HEADER}\n@theme {\n${lines.join('\n')}\n}\n`;
}

/** Nested object per top-level group (one named export each), keys in camelCase (mobileKey). */
function groups(tokens: readonly TokenInput[]): Tree {
  const root: Tree = {};
  for (const token of tokens) {
    const segments = token.path.map(mobileKey);
    if (segments.length < 2) throw new Error(`${token.path.join('.')}: top-level tokens are not supported (group them)`);
    let node = root;
    for (const segment of segments.slice(0, -1)) {
      node[segment] ??= {};
      node = node[segment] as Tree;
    }
    node[segments.slice(-1).join('')] = mobileValue(token);
  }
  return root;
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const key = (name: string): string => (IDENTIFIER.test(name) ? name : JSON.stringify(name));

function jsValue(value: unknown, indent: string): string {
  const inner = `${indent}  `;
  if (Array.isArray(value)) return `Object.freeze([${value.map((item) => jsValue(item, inner)).join(', ')}])`;
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value).map(([name, item]) => `${inner}${key(name)}: ${jsValue(item, inner)},`);
    return `Object.freeze({\n${entries.join('\n')}\n${indent}})`;
  }
  return JSON.stringify(value);
}

function tsType(value: unknown, indent: string): string {
  const inner = `${indent}  `;
  if (Array.isArray(value)) return `readonly [${value.map((item) => tsType(item, inner)).join(', ')}]`;
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value).map(([name, item]) => `${inner}readonly ${key(name)}: ${tsType(item, inner)};`);
    return `{\n${entries.join('\n')}\n${indent}}`;
  }
  return JSON.stringify(value);
}

function mobileJs(exports: Tree): string {
  const blocks = Object.entries(exports).map(([name, tree]) => `export const ${name} = ${jsValue(tree, '')};`);
  return `${HEADER}\n${blocks.join('\n\n')}\n`;
}

function mobileDts(exports: Tree): string {
  const blocks = Object.entries(exports).map(([name, tree]) => `export declare const ${name}: ${tsType(tree, '')};`);
  return `${HEADER}\n${blocks.join('\n\n')}\n`;
}
