import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildTokens, TokenValidationError } from '../src/build.ts';
import { main } from '../src/cli.ts';
import { fixture, VALID } from './helpers.ts';

const DESIGN_TOKENS = fileURLToPath(new URL('../../../design/tokens', import.meta.url));

let out: string;
let css: string;
let js: string;
let dts: string;

beforeAll(async () => {
  out = mkdtempSync(join(tmpdir(), 'evm006-tokens-out-'));
  await buildTokens({ sourceDir: DESIGN_TOKENS, outDir: out });
  css = readFileSync(join(out, 'web', 'tokens.css'), 'utf8');
  js = readFileSync(join(out, 'mobile', 'tokens.js'), 'utf8');
  dts = readFileSync(join(out, 'mobile', 'tokens.d.ts'), 'utf8');
});

afterAll(() => {
  rmSync(out, { recursive: true, force: true });
});

describe('build from design/tokens (EVM-006 AC6)', () => {
  it('EVM-006 AC6: web — :root with --evm- variables of semantic tokens (rem spacing and type, px radii and borders)', () => {
    expect(css).toMatch(/^\/\*\*\n \* Generated by @evia\/tokens/);
    expect(css).toContain(':root {');
    expect(css).toContain('  --evm-color-bg-canvas: #F5F5F5;');
    expect(css).toContain('  --evm-color-bg-scrim: rgba(0, 0, 0, 0.5);');
    expect(css).toContain('  --evm-space-inset-md: 1rem;');
    expect(css).toContain('  --evm-radius-control: 8px;');
    expect(css).toContain('  --evm-border-width-default: 1px;');
    expect(css).toContain('  --evm-text-body-font-size: 1rem;');
    expect(css).toContain('  --evm-text-body-line-height: 1.5;');
    expect(css).toContain('  --evm-motion-easing-standard: cubic-bezier(0.2, 0, 0, 1);');
    expect(css).toMatch(/--evm-text-[a-z0-9-]+-font-variant-numeric: tabular-nums;/);
  });

  it('EVM-006 AC6: base tokens and deprecated tokens are not exported (web and mobile)', () => {
    for (const output of [css, js, dts]) {
      expect(output).not.toMatch(/palette|dimension-16|evm-font-size|breakpoint/);
    }
    expect(css).not.toContain('--evm-color-status-order-quote-');
    expect(css).not.toContain('--evm-color-status-payment-issued-');
    expect(css).toContain('--evm-color-status-order-quoting-bg:');
    expect(css).toContain('--evm-color-status-payment-invoiced-bg:');
  });

  it('EVM-006 AC6: mobile — ESM constants (dp numbers, hex colors, React Native text styles) importable by the app', async () => {
    const tokens = (await import(pathToFileURL(join(out, 'mobile', 'tokens.js')).href)) as Record<string, Record<string, unknown>>;
    expect(Object.keys(tokens).sort()).toEqual(['borderWidth', 'color', 'elevation', 'layer', 'motion', 'radius', 'size', 'space', 'text']);
    expect(tokens['space']).toMatchObject({ inset: { md: 16 } });
    expect(tokens['color']).toMatchObject({
      bg: { canvas: '#F5F5F5' },
      status: { order: { inProgress: { bg: expect.stringMatching(/^#/) as unknown } } },
    });
    expect(tokens['text']).toMatchObject({ body: { fontFamily: 'Inter', fontSize: 16, fontWeight: '400', lineHeight: 24 } });
    expect(tokens['color']).not.toHaveProperty('status.order.quote');
    expect(Object.isFrozen(tokens['color'])).toBe(true);
  });

  it('EVM-006 AC6: mobile types are literal and readonly; the package ships no .ts sources', () => {
    expect(dts).toContain('export declare const space: {');
    expect(dts).toMatch(/readonly md: 16;/);
    expect(dts).toMatch(/readonly canvas: "#F5F5F5";/);
    expect(js).not.toMatch(/: (string|number);/);
  });

  it('EVM-006 AC6: the build is deterministic (two builds give identical files)', async () => {
    const second = mkdtempSync(join(tmpdir(), 'evm006-tokens-out2-'));
    try {
      await buildTokens({ sourceDir: DESIGN_TOKENS, outDir: second });
      for (const file of ['web/tokens.css', 'mobile/tokens.js', 'mobile/tokens.d.ts']) {
        expect(readFileSync(join(second, file), 'utf8')).toBe(readFileSync(join(out, file), 'utf8'));
      }
    } finally {
      rmSync(second, { recursive: true, force: true });
    }
  });
});

describe('build errors (EVM-006 AC6)', () => {
  it('EVM-006 AC6: a validation error stops the build with the full list of errors and writes nothing', async () => {
    const source = fixture({
      ...VALID,
      'semantic/bad.tokens.json': {
        layer: { $type: 'number', top: { $value: 1 } },
        space: { lg: { $type: 'dimension', $value: '{nope}' } },
      },
    });
    const target = mkdtempSync(join(tmpdir(), 'evm006-tokens-bad-'));
    try {
      const failure = await buildTokens({ sourceDir: source.dir, outDir: target }).catch((error: unknown) => error);
      expect(failure).toBeInstanceOf(TokenValidationError);
      expect((failure as TokenValidationError).errors).toEqual([
        'semantic/bad.tokens.json: layer.top — literal value in semantic/ (use an alias to a base token)',
        'semantic/bad.tokens.json: space.lg — alias {nope} does not resolve',
      ]);
      expect(readdirSync(target)).toEqual([]);
    } finally {
      source.dispose();
      rmSync(target, { recursive: true, force: true });
    }
  });

  it('EVM-006 AC6: a group split across files is merged into one export', async () => {
    const source = fixture({
      ...VALID,
      'semantic/space-extra.tokens.json': { space: { $type: 'dimension', lg: { $value: '{dimension.16}' } } },
    });
    try {
      await buildTokens({ sourceDir: source.dir, outDir: join(source.dir, 'dist') });
      const web = readFileSync(join(source.dir, 'dist', 'web', 'tokens.css'), 'utf8');
      expect(web).toContain('--evm-space-md: 1rem;');
      expect(web).toContain('--evm-space-lg: 1rem;');
    } finally {
      source.dispose();
    }
  });

  it('EVM-006 AC6: a semantic token at the top level (outside any group) is rejected', async () => {
    const source = fixture({ ...VALID, 'semantic/gap.tokens.json': { gap: { $type: 'dimension', $value: '{dimension.8}' } } });
    try {
      await expect(buildTokens({ sourceDir: source.dir, outDir: join(source.dir, 'dist') })).rejects.toThrow(
        /top-level tokens are not supported/,
      );
    } finally {
      source.dispose();
    }
  });

  it('EVM-006 AC6: an empty token directory is an error (nothing to build)', async () => {
    const source = fixture({});
    try {
      await expect(buildTokens({ sourceDir: source.dir, outDir: join(source.dir, 'dist') })).rejects.toThrow(/no \*\.tokens\.json/);
    } finally {
      source.dispose();
    }
  });
});

describe('build entry point (EVM-006 AC6)', () => {
  it('EVM-006 AC6: prints the outputs and returns 0; on validation errors prints them and returns 1', async () => {
    const good = fixture(VALID);
    const bad = fixture({ ...VALID, 'semantic/bad.tokens.json': { space: { lg: { $type: 'dimension', $value: '{nope}' } } } });
    try {
      const lines: string[] = [];
      const io = { stdout: (line: string) => lines.push(`out ${line}`), stderr: (line: string) => lines.push(`err ${line}`) };
      expect(await main({ sourceDir: good.dir, outDir: join(good.dir, 'dist'), ...io })).toBe(0);
      expect(lines.at(-1)).toMatch(/^out @evia\/tokens: 3 files/);
      expect(await main({ sourceDir: bad.dir, outDir: join(bad.dir, 'dist'), ...io })).toBe(1);
      expect(lines.at(-1)).toBe('err   semantic/bad.tokens.json: space.lg — alias {nope} does not resolve');
    } finally {
      good.dispose();
      bad.dispose();
    }
  });

  it('EVM-006 AC6: other build failures are not hidden behind exit code 1', async () => {
    const empty = fixture({});
    try {
      const io = { stdout: () => undefined, stderr: () => undefined };
      await expect(main({ sourceDir: empty.dir, outDir: join(empty.dir, 'dist'), ...io })).rejects.toThrow(/no \*\.tokens\.json/);
    } finally {
      empty.dispose();
    }
  });
});
