/**
 * 0011 — customers schema (ADR-0003, ADR-0017; EVM-020): the table `customers.customers`. Expand only. Rules:
 * - `id` is NOT generated by the database: the client sends a UUIDv7 (so a retried save names the same customer); the CHECK
 *   `uuid_extract_version(id) = 7` is the last line of defence — the contract answers 400 first, so a violation is never a 500;
 * - `kind` is `person` or `company`; a CHECK says which columns belong to which kind (a person has both names, a company a
 *   name, and none holds the columns of the other kind); lengths are bounded in the database as in the contract (200, notes 2000);
 * - the postal address is five columns of the model (`street`, `building_number`, `apartment_number`, `postal_code`, `city`),
 *   all or none of street/building/postal code/city; the apartment number only with a street;
 * - `display_name` and `sort_name` (surname before the first name) are STORED generated columns; `search_text` is
 *   `f_unaccent(lower(…))` of the first name, surname, company, NIP, the DIGITS of the telephone, e-mail and city — no notes, no
 *   contact person (SR-DATA-03). It holds a telephone number and an e-mail address (DO-K): it is never returned or logged;
 * - the index is GIN `gin_trgm_ops` on `search_text`, partial `deleted_at IS NULL` (what every read condition says); there is no
 *   index on the telephone: the "similar customer" prompt uses the same trigram search (YAGNI);
 * - the application role gets SELECT, INSERT and UPDATE (soft delete only: no DELETE); the read-only role has no access.
 * Times are written by the application (no `now()` defaults), as in `work_orders`.
 */
import { sql, type Kysely } from 'kysely';
import type { Database } from '../platform/database/database.ts';

export async function up(db: Kysely<Database>): Promise<void> {
  await sql`create schema customers`.execute(db);
  await sql`revoke all on schema customers from public`.execute(db);

  await sql`
    create table customers.customers (
      id uuid primary key check (uuid_extract_version(id) = 7),
      kind text not null check (kind in ('person', 'company')),
      first_name text check (length(first_name) between 1 and 200),
      last_name text check (length(last_name) between 1 and 200),
      company_name text check (length(company_name) between 1 and 200),
      tax_id text check (tax_id ~ '^[0-9]{10}$'),
      contact_person_name text check (length(contact_person_name) between 1 and 200),
      phone text not null check (phone ~ '^\\+[1-9][0-9]{7,14}$'),
      email text check (length(email) between 3 and 254 and email = lower(email)),
      street text check (length(street) between 1 and 200),
      building_number text check (length(building_number) between 1 and 20),
      apartment_number text check (length(apartment_number) between 1 and 20),
      postal_code text check (postal_code ~ '^[0-9]{2}-[0-9]{3}$'),
      city text check (length(city) between 1 and 100),
      notes text check (length(notes) between 1 and 2000),
      display_name text generated always as (
        case kind when 'person' then first_name || ' ' || last_name else company_name end
      ) stored,
      sort_name text generated always as (
        case kind when 'person' then last_name || ' ' || first_name else company_name end
      ) stored,
      search_text text generated always as (
        public.f_unaccent(
          lower(
            coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(company_name, '') || ' ' ||
            coalesce(tax_id, '') || ' ' || regexp_replace(phone, '\\D', '', 'g') || ' ' || coalesce(email, '') || ' ' ||
            coalesce(city, '')
          )
        )
      ) stored,
      created_at timestamptz not null,
      created_by uuid,
      updated_at timestamptz not null,
      updated_by uuid,
      version integer not null default 1 check (version >= 1),
      deleted_at timestamptz,
      deleted_by uuid,
      constraint customers_kind_columns check (
        case kind
          when 'person' then first_name is not null and last_name is not null
            and company_name is null and tax_id is null and contact_person_name is null
          else company_name is not null and first_name is null and last_name is null
        end
      ),
      constraint customers_address_together check (
        (street is null) = (building_number is null) and (street is null) = (postal_code is null)
          and (street is null) = (city is null) and (apartment_number is null or street is not null)
      )
    )
  `.execute(db);
  await sql`
    create index customers_search_text_trgm_idx on customers.customers using gin (search_text public.gin_trgm_ops)
      where deleted_at is null
  `.execute(db);

  await sql`grant usage on schema customers to evia_app`.execute(db);
  await sql`grant select, insert, update on customers.customers to evia_app`.execute(db);
}
