/**
 * 0013 — parties schema (ADR-0003, ADR-0017; EVM-021): the table `parties.parties`. Expand only. Rules:
 * - `id` is NOT generated by the database: the client sends a UUIDv7 (so a retried save names the same party); the CHECK
 *   `uuid_extract_version(id) = 7` is the last line of defence — the contract answers 400 first, so a violation is never a 500;
 * - `kind` holds the ten values of `PartyKind` and `legal_form` the two of the model, as CHECKs (a new value is an *expand*:
 *   a new migration relaxing the CHECK); lengths are bounded in the database as in the contract (200, notes 2000);
 * - the telephone is E.164 and the e-mail lower case, as in `customers` (the application normalises, the CHECK is the last
 *   line); both are optional — a party need not have either;
 * - `search_text` is `f_unaccent(lower(…))` of the display name and the contact person: no telephone, no e-mail, no notes — it
 *   is narrower than the "searchable fields" of the model on purpose (minimisation, SR-DATA-03). It holds the name of a natural
 *   person (DO-3): it is never returned or logged;
 * - the index is GIN `gin_trgm_ops` on `search_text`, partial `deleted_at IS NULL` (what every read condition says);
 * - the application role gets SELECT, INSERT and UPDATE (soft delete only: no DELETE); the read-only role has no access.
 * Times are written by the application (no `now()` defaults), as in `customers`. Nothing is migrated: the table is new.
 */
import { sql, type Kysely } from 'kysely';
import type { Database } from '../platform/database/database.ts';

export async function up(db: Kysely<Database>): Promise<void> {
  await sql`create schema parties`.execute(db);
  await sql`revoke all on schema parties from public`.execute(db);

  await sql`
    create table parties.parties (
      id uuid primary key check (uuid_extract_version(id) = 7),
      kind text not null check (kind in (
        'building_administration', 'property_manager', 'housing_community', 'designer', 'fire_safety_expert',
        'technical_expert', 'distribution_system_operator', 'subcontractor', 'supplier', 'other'
      )),
      legal_form text not null check (legal_form in ('organization', 'natural_person')),
      display_name text not null check (length(display_name) between 1 and 200),
      contact_person_name text check (length(contact_person_name) between 1 and 200),
      phone text check (phone ~ '^\\+[1-9][0-9]{7,14}$'),
      email text check (length(email) between 3 and 254 and email = lower(email)),
      notes text check (length(notes) between 1 and 2000),
      search_text text generated always as (
        public.f_unaccent(lower(display_name || ' ' || coalesce(contact_person_name, '')))
      ) stored,
      created_at timestamptz not null,
      created_by uuid,
      updated_at timestamptz not null,
      updated_by uuid,
      version integer not null default 1 check (version >= 1),
      deleted_at timestamptz,
      deleted_by uuid
    )
  `.execute(db);
  await sql`
    create index parties_search_text_trgm_idx on parties.parties using gin (search_text public.gin_trgm_ops)
      where deleted_at is null
  `.execute(db);

  await sql`grant usage on schema parties to evia_app`.execute(db);
  await sql`grant select, insert, update on parties.parties to evia_app`.execute(db);
}
