/**
 * 0014 — sites schema (ADR-0003, ADR-0017; EVM-021): the table `sites.sites`. Expand only; `Charger` is not here (M4/M7). Rules:
 * - `id` is NOT generated by the database: the client sends a UUIDv7; the CHECK `uuid_extract_version(id) = 7` is the last line
 *   of defence (the contract answers 400 first);
 * - a site is independent of any customer (D7): there is no `customer_id`;
 * - `site_type` holds the four values of `SiteType`; the parking spot and the level exist only for `multi_family_garage`
 *   (the CHECK repeats the rule of the domain); the postal code is `NN-NNN`; the connection power is `numeric(6,2)`, greater
 *   than 0 and at most 1000 kW (an assumption of the product owner to confirm — EVM-021 note); the PPE has at most 40 characters;
 * - the OSD and the manager are foreign keys to `parties.parties` with `ON DELETE RESTRICT` (no cascade: a party is soft deleted,
 *   and a delete that would leave a site without it fails); that the OSD is of kind OSD and the manager of a manager kind is a rule
 *   of the application, checked in the transaction of the insert (the CHECK of a database cannot see another table);
 * - `search_text` is `f_unaccent(lower(…))` of the street, the building and apartment numbers, the postal code, the city and the
 *   parking spot: no PPE, no notes (SR-DATA-03). It holds the address of a home (DO-K): it is never returned or logged;
 * - the index is GIN `gin_trgm_ops` on `search_text`, partial `deleted_at IS NULL` (what every read condition says);
 * - the application role gets SELECT, INSERT and UPDATE (soft delete only: no DELETE); the read-only role has no access.
 * Times are written by the application (no `now()` defaults). Nothing is migrated: the table is new.
 */
import { sql, type Kysely } from 'kysely';
import type { Database } from '../platform/database/database.ts';

export async function up(db: Kysely<Database>): Promise<void> {
  await sql`create schema sites`.execute(db);
  await sql`revoke all on schema sites from public`.execute(db);

  await sql`
    create table sites.sites (
      id uuid primary key check (uuid_extract_version(id) = 7),
      site_type text not null check (site_type in ('single_family_house', 'multi_family_garage', 'commercial', 'other')),
      street text not null check (length(street) between 1 and 200),
      building_number text not null check (length(building_number) between 1 and 20),
      apartment_number text check (length(apartment_number) between 1 and 20),
      postal_code text not null check (postal_code ~ '^[0-9]{2}-[0-9]{3}$'),
      city text not null check (length(city) between 1 and 100),
      parking_spot_number text check (length(parking_spot_number) between 1 and 20),
      garage_level text check (length(garage_level) between 1 and 20),
      connection_power_kw numeric(6, 2) check (connection_power_kw > 0 and connection_power_kw <= 1000),
      metering_point_id text check (length(metering_point_id) between 1 and 40),
      distribution_system_operator_party_id uuid references parties.parties (id) on delete restrict,
      manager_party_id uuid references parties.parties (id) on delete restrict,
      notes text check (length(notes) between 1 and 2000),
      search_text text generated always as (
        public.f_unaccent(
          lower(
            street || ' ' || building_number || ' ' || coalesce(apartment_number, '') || ' ' || postal_code || ' ' || city || ' ' ||
            coalesce(parking_spot_number, '')
          )
        )
      ) stored,
      created_at timestamptz not null,
      created_by uuid,
      updated_at timestamptz not null,
      updated_by uuid,
      version integer not null default 1 check (version >= 1),
      deleted_at timestamptz,
      deleted_by uuid,
      constraint sites_garage_columns check (
        (parking_spot_number is null and garage_level is null) or site_type = 'multi_family_garage'
      )
    )
  `.execute(db);
  await sql`
    create index sites_search_text_trgm_idx on sites.sites using gin (search_text public.gin_trgm_ops)
      where deleted_at is null
  `.execute(db);

  await sql`grant usage on schema sites to evia_app`.execute(db);
  await sql`grant select, insert, update on sites.sites to evia_app`.execute(db);
}
