/**
 * Kysely types of the table the `parties` module owns (EVM-021). `platform` does not know module tables: the module narrows a
 * handle with `db.$extendTables<PartyTables>()`. The application role has SELECT, INSERT and UPDATE (no DELETE: soft delete
 * only). `search_text` is generated by the database — it can be read, never written.
 */
import type { Generated, GeneratedAlways, Kysely } from 'kysely';
import type { Database } from '../../../platform/database/database.ts';
import type { PartyKind, PartyLegalForm } from '../domain/party.ts';

export interface PartiesTable {
  id: string;
  kind: PartyKind;
  legal_form: PartyLegalForm;
  display_name: string;
  contact_person_name: string | null;
  phone: string | null;
  email: string | null;
  notes: string | null;
  search_text: GeneratedAlways<string>;
  created_at: Date;
  created_by: string | null;
  updated_at: Date;
  updated_by: string | null;
  version: Generated<number>;
  deleted_at: Date | null;
  deleted_by: string | null;
}

export type PartyTables = { 'parties.parties': PartiesTable };

export type PartiesDb = Kysely<PartyTables>;

export const partyTables = (db: Kysely<Database>): PartiesDb => db.$extendTables<PartyTables>();
