import { sql } from 'kysely';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { migratedDatabase, type MigratedDatabase } from './database.ts';

let database: MigratedDatabase;
beforeAll(async () => {
  database = await migratedDatabase();
});
afterAll(async () => {
  await database.close();
});

const admin = () => database.admin;
const T = '2026-10-07T08:00:00Z';
const V7 = (n: number): string => `0198b0a0-0000-7000-8000-${String(n).padStart(12, '0')}`;
const fails = async (statement: Promise<unknown>, code: string): Promise<void> => {
  await expect(statement).rejects.toMatchObject({ code });
};

interface Spec {
  id?: string;
  kind?: string;
  firstName?: string | null;
  lastName?: string | null;
  companyName?: string | null;
  taxId?: string | null;
  contact?: string | null;
  phone?: string;
  email?: string | null;
  street?: string | null;
  building?: string | null;
  apartment?: string | null;
  postalCode?: string | null;
  city?: string | null;
  notes?: string | null;
}
let counter = 100;
const insert = (spec: Spec = {}) => {
  const kind = spec.kind ?? 'person';
  const person = kind === 'person';
  const value = <K extends keyof Spec>(key: K, fallback: Spec[K]): Spec[K] => (key in spec ? spec[key] : fallback);
  counter += 1;
  return sql`
    insert into customers.customers (id, kind, first_name, last_name, company_name, tax_id, contact_person_name, phone, email,
      street, building_number, apartment_number, postal_code, city, notes, created_at, updated_at)
    values (${spec.id ?? V7(counter)}, ${kind}, ${value('firstName', person ? 'Jan' : null)}, ${value('lastName', person ? 'Przykładowy' : null)},
      ${value('companyName', person ? null : 'Firma Testowa')}, ${value('taxId', null)}, ${value('contact', null)}, ${spec.phone ?? '+48600000001'},
      ${value('email', null)}, ${value('street', null)}, ${value('building', null)}, ${value('apartment', null)}, ${value('postalCode', null)},
      ${value('city', null)}, ${value('notes', null)}, ${T}, ${T})`.execute(admin());
};
const address = { street: 'Piotrkowska', building: '1', postalCode: '90-001', city: 'Łódź' };

describe('migration 0011 — customers (EVM-020 AC1, AC2, AC5, AC7; ADR-0003; expand only)', () => {
  it('EVM-020 AC2 the table has the columns of the model: the address as five columns, generated names and search text, the common columns', async () => {
    const { rows } = await sql<{ column_name: string }>`
      select column_name from information_schema.columns where table_schema = 'customers' and table_name = 'customers' order by ordinal_position`.execute(
      admin(),
    );
    expect(rows.map((row) => row.column_name)).toEqual([
      'id',
      'kind',
      'first_name',
      'last_name',
      'company_name',
      'tax_id',
      'contact_person_name',
      'phone',
      'email',
      'street',
      'building_number',
      'apartment_number',
      'postal_code',
      'city',
      'notes',
      'display_name',
      'sort_name',
      'search_text',
      'created_at',
      'created_by',
      'updated_at',
      'updated_by',
      'version',
      'deleted_at',
      'deleted_by',
    ]);
  });

  it('EVM-020 AC4 the id must be a UUIDv7 (CHECK) and is never generated by the database', async () => {
    await insert({ id: V7(1) });
    await fails(insert({ id: V7(1) }), '23505');
    await fails(insert({ id: '0198b0a0-0000-4000-8000-000000000002' }), '23514');
    const { rows } = await sql<{ column_default: string | null }>`
      select column_default from information_schema.columns where table_schema = 'customers' and column_name = 'id'`.execute(admin());
    expect(rows[0]?.column_default).toBeNull();
  });

  it('EVM-020 AC2 the kind decides the columns: a person has both names and no company column, a company a name and no person column', async () => {
    await fails(insert({ kind: 'organisation' }), '23514');
    await fails(insert({ firstName: null }), '23514');
    await fails(insert({ lastName: null }), '23514');
    await fails(insert({ companyName: 'X' }), '23514');
    await fails(insert({ taxId: '5260250274' }), '23514');
    await fails(insert({ contact: 'Anna' }), '23514');
    await insert({ kind: 'company', taxId: '5260250274', contact: 'Anna Kontaktowa' });
    await fails(insert({ kind: 'company', companyName: null }), '23514');
    await fails(insert({ kind: 'company', firstName: 'Jan' }), '23514');
    await fails(insert({ kind: 'company', lastName: 'K' }), '23514');
  });

  it('EVM-020 AC5 lengths: a name of 200 characters passes, 201 and an empty text fail; notes 2000; the NIP is 10 digits; the e-mail lower case', async () => {
    await insert({ lastName: 'N'.repeat(200) });
    await fails(insert({ lastName: 'N'.repeat(201) }), '23514');
    await fails(insert({ lastName: '' }), '23514');
    await insert({ notes: 'n'.repeat(2000) });
    await fails(insert({ notes: 'n'.repeat(2001) }), '23514');
    await fails(insert({ kind: 'company', taxId: '123' }), '23514');
    await insert({ email: 'jan@example.test' });
    await fails(insert({ email: 'Jan@Example.test' }), '23514');
    await fails(insert({ email: 'a' }), '23514');
  });

  it('EVM-020 AC2 the telephone is E.164 and required', async () => {
    for (const phone of ['600000001', '+0600000001', '+48 600 000 001', '+4860000000a', '+123456']) await fails(insert({ phone }), '23514');
    await insert({ phone: '+442079460958' });
  });

  it('EVM-020 AC2 the postal address is all or none of street, building, postal code and city; the apartment needs a street; the code is 00-000', async () => {
    await insert({ ...address, apartment: '5' });
    await fails(insert({ ...address, street: null }), '23514');
    await fails(insert({ ...address, city: null }), '23514');
    await fails(insert({ ...address, postalCode: '90001' }), '23514');
    await fails(insert({ apartment: '5' }), '23514');
  });

  it('EVM-020 AC1 display name, sort name (surname first) and the search text are generated: no notes, no contact person, the telephone as digits, accents removed', async () => {
    await insert({
      id: V7(50),
      lastName: 'Łukasiewicz',
      firstName: 'Zażółć',
      email: 'jan@example.test',
      ...address,
      notes: 'sekretna notatka',
      phone: '+48600000050',
    });
    await insert({ id: V7(51), kind: 'company', companyName: 'Firma Testowa sp. z o.o.', taxId: '5260250274', contact: 'Anna Kontaktowa' });
    const { rows } = await sql<{ id: string; display_name: string; sort_name: string; search_text: string }>`
      select id, display_name, sort_name, trim(regexp_replace(search_text, '\\s+', ' ', 'g')) as search_text from customers.customers where id in (${V7(50)}, ${V7(51)}) order by id`.execute(
      admin(),
    );
    expect(rows[0]).toEqual({
      id: V7(50),
      display_name: 'Zażółć Łukasiewicz',
      sort_name: 'Łukasiewicz Zażółć',
      search_text: 'zazolc lukasiewicz 48600000050 jan@example.test lodz',
    });
    expect(rows[1]).toEqual({
      id: V7(51),
      display_name: 'Firma Testowa sp. z o.o.',
      sort_name: 'Firma Testowa sp. z o.o.',
      search_text: 'firma testowa sp. z o.o. 5260250274 48600000001',
    });
    const text = rows.map((row) => row.search_text).join('|');
    expect(text).not.toContain('sekretna');
    expect(text).not.toContain('kontaktowa');
  });

  it('EVM-020 AC1 the sort name sorts in the ICU collation pl-PL of the database: Ł after L and before M (not bytewise)', async () => {
    for (const [index, lastName] of ['Mazur', 'Łukasiewicz', 'Lis', 'Zawada'].entries())
      await insert({ id: V7(70 + index), lastName, firstName: 'Ola' });
    const { rows } = await sql<{ sort_name: string }>`
      select sort_name from customers.customers where id between ${V7(70)} and ${V7(73)} order by sort_name, id`.execute(admin());
    expect(rows.map((row) => row.sort_name)).toEqual(['Lis Ola', 'Łukasiewicz Ola', 'Mazur Ola', 'Zawada Ola']);
  });

  it('EVM-020 AC1 the only index besides the key is a partial GIN trigram index on the search text (deleted_at is null); none on the telephone', async () => {
    const { rows } = await sql<{ indexname: string; indexdef: string }>`
      select indexname, indexdef from pg_indexes where schemaname = 'customers' order by indexname`.execute(admin());
    expect(rows.map((row) => row.indexname)).toEqual(['customers_pkey', 'customers_search_text_trgm_idx']);
    const trigram = rows.find((row) => row.indexname === 'customers_search_text_trgm_idx')?.indexdef ?? '';
    expect(trigram).toMatch(/USING gin \(search_text gin_trgm_ops\) WHERE \(deleted_at IS NULL\)/);
  });

  it('EVM-020 AC1 a search by 3 or more characters uses the trigram index (the planner is forced off the sequential scan: the table is small)', async () => {
    const plan = await admin()
      .transaction()
      .execute(async (tx) => {
        await sql`set local enable_seqscan = off`.execute(tx);
        const { rows } = await sql<{ 'QUERY PLAN': string }>`
        explain select id from customers.customers
        where deleted_at is null and search_text ilike '%' || public.f_unaccent(lower(${'lodz'})) || '%' escape '\\'`.execute(tx);
        return rows.map((row) => row['QUERY PLAN']).join('\n');
      });
    expect(plan).toContain('customers_search_text_trgm_idx');
  });

  it('EVM-020 AC7 the application role may SELECT, INSERT and UPDATE customers but not DELETE or TRUNCATE; PUBLIC has no access to the schema', async () => {
    const { rows } = await sql<Record<string, boolean>>`
      select has_table_privilege('evia_it_app', 'customers.customers', 'SELECT') as "select", has_table_privilege('evia_it_app', 'customers.customers', 'INSERT') as "insert",
             has_table_privilege('evia_it_app', 'customers.customers', 'UPDATE') as "update", has_table_privilege('evia_it_app', 'customers.customers', 'DELETE') as "delete",
             has_table_privilege('evia_it_app', 'customers.customers', 'TRUNCATE') as "truncate",
             has_schema_privilege('public', 'customers', 'USAGE') as "public_usage", has_schema_privilege('evia_it_app', 'customers', 'CREATE') as "app_create"`.execute(
      admin(),
    );
    expect(rows[0]).toEqual({
      select: true,
      insert: true,
      update: true,
      delete: false,
      truncate: false,
      public_usage: false,
      app_create: false,
    });
  });
});

describe('migration 0012 — idempotency records (EVM-020 AC4; SR-API-05; expand only)', () => {
  const USER = V7(900);
  const KEY = V7(901);
  const record = (overrides: { device?: string | null; key?: string; hash?: string; status?: number } = {}) =>
    sql`insert into platform.idempotency_records (user_id, device_id, idempotency_key, scope, request_hash, result_status, result_code, result_resource_id, created_at, expires_at)
        values (${USER}, ${overrides.device ?? null}, ${overrides.key ?? KEY}, 'POST /api/v1/customers', ${overrides.hash ?? 'a'.repeat(64)},
                ${overrides.status ?? 201}, 'created', ${V7(902)}, ${T}, '2026-11-06T08:00:00Z')`.execute(admin());

  it('EVM-020 AC4 the key is unique per (user, device) and a missing device (the web) counts as one value, not as always different', async () => {
    await record();
    await fails(record(), '23505');
    await record({ device: V7(903) });
    await fails(record({ device: V7(903) }), '23505');
    await record({ key: V7(904) });
  });

  it('EVM-020 AC4 only a successful result is stored (2xx) and the hash is 64 hex digits', async () => {
    await fails(record({ key: V7(910), status: 409 }), '23514');
    await fails(record({ key: V7(911), status: 500 }), '23514');
    await fails(record({ key: V7(912), hash: 'xyz' }), '23514');
  });

  it('EVM-020 AC4 the application role may SELECT, INSERT and UPDATE the records but not DELETE (the cleanup job brings DELETE)', async () => {
    const { rows } = await sql<Record<string, boolean>>`
      select has_table_privilege('evia_it_app', 'platform.idempotency_records', 'SELECT') as "select", has_table_privilege('evia_it_app', 'platform.idempotency_records', 'INSERT') as "insert",
             has_table_privilege('evia_it_app', 'platform.idempotency_records', 'UPDATE') as "update", has_table_privilege('evia_it_app', 'platform.idempotency_records', 'DELETE') as "delete",
             has_table_privilege('evia_it_app', 'platform.idempotency_records', 'TRUNCATE') as "truncate"`.execute(admin());
    expect(rows[0]).toEqual({ select: true, insert: true, update: true, delete: false, truncate: false });
  });
});
