import { sql } from 'kysely';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { migratedDatabase, type MigratedDatabase } from './database.ts';

let database: MigratedDatabase;
beforeAll(async () => {
  database = await migratedDatabase();
});
afterAll(async () => {
  await database.close();
});

const admin = () => database.admin;
const T = '2026-10-07T08:00:00Z';
const V7 = (n: number): string => `0198b0a0-0000-7000-8000-${String(n).padStart(12, '0')}`;
const fails = async (statement: Promise<unknown>, code: string): Promise<void> => {
  await expect(statement).rejects.toMatchObject({ code });
};

interface PartySpec {
  id?: string;
  kind?: string;
  legalForm?: string;
  displayName?: string;
  contact?: string | null;
  phone?: string | null;
  email?: string | null;
  notes?: string | null;
}
let partyCounter = 100;
const insertParty = (spec: PartySpec = {}) => {
  const value = <K extends keyof PartySpec>(key: K, fallback: PartySpec[K]): PartySpec[K] => (key in spec ? spec[key] : fallback);
  partyCounter += 1;
  return sql`
    insert into parties.parties (id, kind, legal_form, display_name, contact_person_name, phone, email, notes, created_at, updated_at)
    values (${spec.id ?? V7(partyCounter)}, ${spec.kind ?? 'distribution_system_operator'}, ${spec.legalForm ?? 'organization'},
      ${spec.displayName ?? 'Operator Testowy'}, ${value('contact', null)}, ${value('phone', null)}, ${value('email', null)},
      ${value('notes', null)}, ${T}, ${T})`.execute(admin());
};

interface SiteSpec {
  id?: string;
  siteType?: string;
  street?: string;
  building?: string;
  apartment?: string | null;
  postalCode?: string;
  city?: string;
  spot?: string | null;
  level?: string | null;
  power?: number | null;
  ppe?: string | null;
  osd?: string | null;
  manager?: string | null;
  notes?: string | null;
}
let siteCounter = 500;
const insertSite = (spec: SiteSpec = {}) => {
  const value = <K extends keyof SiteSpec>(key: K, fallback: SiteSpec[K]): SiteSpec[K] => (key in spec ? spec[key] : fallback);
  siteCounter += 1;
  return sql`
    insert into sites.sites (id, site_type, street, building_number, apartment_number, postal_code, city, parking_spot_number,
      garage_level, connection_power_kw, metering_point_id, distribution_system_operator_party_id, manager_party_id, notes,
      created_at, updated_at)
    values (${spec.id ?? V7(siteCounter)}, ${spec.siteType ?? 'single_family_house'}, ${spec.street ?? 'ul. Testowa'}, ${spec.building ?? '7'},
      ${value('apartment', null)}, ${spec.postalCode ?? '00-001'}, ${spec.city ?? 'Warszawa'}, ${value('spot', null)}, ${value('level', null)},
      ${value('power', null)}, ${value('ppe', null)}, ${value('osd', null)}, ${value('manager', null)}, ${value('notes', null)}, ${T}, ${T})`.execute(
    admin(),
  );
};

describe('migration 0013 — parties (EVM-021 AC3, AC4, AC5, AC6; ADR-0003; expand only)', () => {
  it('EVM-021 AC4 the table has the columns of the model, a generated search text and the common columns', async () => {
    const { rows } = await sql<{ column_name: string }>`
      select column_name from information_schema.columns where table_schema = 'parties' and table_name = 'parties' order by ordinal_position`.execute(
      admin(),
    );
    expect(rows.map((row) => row.column_name)).toEqual([
      'id',
      'kind',
      'legal_form',
      'display_name',
      'contact_person_name',
      'phone',
      'email',
      'notes',
      'search_text',
      'created_at',
      'created_by',
      'updated_at',
      'updated_by',
      'version',
      'deleted_at',
      'deleted_by',
    ]);
  });

  it('EVM-021 AC4 the id must be a UUIDv7 (CHECK) and is never generated by the database', async () => {
    await insertParty({ id: V7(1) });
    await fails(insertParty({ id: V7(1) }), '23505');
    await fails(insertParty({ id: '0198b0a0-0000-4000-8000-000000000002' }), '23514');
    const { rows } = await sql<{ column_default: string | null }>`
      select column_default from information_schema.columns where table_schema = 'parties' and column_name = 'id'`.execute(admin());
    expect(rows[0]?.column_default).toBeNull();
  });

  it('EVM-021 AC3 the kind is one of the ten values of PartyKind and the form one of the two of the model', async () => {
    for (const kind of [
      'building_administration',
      'property_manager',
      'housing_community',
      'designer',
      'fire_safety_expert',
      'technical_expert',
      'distribution_system_operator',
      'subcontractor',
      'supplier',
      'other',
    ])
      await insertParty({ kind });
    await fails(insertParty({ kind: 'osd' }), '23514');
    await insertParty({ legalForm: 'natural_person' });
    await fails(insertParty({ legalForm: 'person' }), '23514');
  });

  it('EVM-021 AC5 lengths: a name of 200 characters passes, 201 and an empty one fail; notes 2000; the telephone is E.164; the e-mail lower case', async () => {
    await insertParty({ displayName: 'N'.repeat(200) });
    await fails(insertParty({ displayName: 'N'.repeat(201) }), '23514');
    await fails(insertParty({ displayName: '' }), '23514');
    await fails(insertParty({ contact: 'C'.repeat(201) }), '23514');
    await insertParty({ notes: 'n'.repeat(2000) });
    await fails(insertParty({ notes: 'n'.repeat(2001) }), '23514');
    await insertParty({ phone: '+48600000001', email: 'biuro@example.test' });
    await fails(insertParty({ phone: '600000001' }), '23514');
    await fails(insertParty({ email: 'Biuro@Example.test' }), '23514');
  });

  it('EVM-021 AC1 the search text is generated from the name and the contact person only: no telephone, e-mail or notes, accents removed', async () => {
    await insertParty({
      id: V7(50),
      displayName: 'Łódzki Operator Sp. z o.o.',
      contact: 'Zażółć Gęślą',
      phone: '+48600000050',
      email: 'sekret@example.test',
      notes: 'sekretna notatka',
    });
    await insertParty({ id: V7(51), displayName: 'Bez osoby' });
    const { rows } = await sql<{ id: string; search_text: string }>`
      select id, trim(regexp_replace(search_text, '\\s+', ' ', 'g')) as search_text from parties.parties where id in (${V7(50)}, ${V7(51)}) order by id`.execute(
      admin(),
    );
    expect(rows).toEqual([
      { id: V7(50), search_text: 'lodzki operator sp. z o.o. zazolc gesla' },
      { id: V7(51), search_text: 'bez osoby' },
    ]);
  });

  it('EVM-021 AC1 the only index besides the key is a partial GIN trigram index on the search text (deleted_at is null)', async () => {
    const { rows } = await sql<{ indexname: string; indexdef: string }>`
      select indexname, indexdef from pg_indexes where schemaname = 'parties' order by indexname`.execute(admin());
    expect(rows.map((row) => row.indexname)).toEqual(['parties_pkey', 'parties_search_text_trgm_idx']);
    expect(rows[1]?.indexdef).toMatch(/USING gin \(search_text gin_trgm_ops\) WHERE \(deleted_at IS NULL\)/);
  });

  it('EVM-021 AC6 the application role may SELECT, INSERT and UPDATE parties but not DELETE or TRUNCATE; PUBLIC has no access to the schema', async () => {
    const { rows } = await sql<Record<string, boolean>>`
      select has_table_privilege('evia_it_app', 'parties.parties', 'SELECT') as "select", has_table_privilege('evia_it_app', 'parties.parties', 'INSERT') as "insert",
             has_table_privilege('evia_it_app', 'parties.parties', 'UPDATE') as "update", has_table_privilege('evia_it_app', 'parties.parties', 'DELETE') as "delete",
             has_table_privilege('evia_it_app', 'parties.parties', 'TRUNCATE') as "truncate", has_table_privilege('evia_it_app', 'parties.parties', 'REFERENCES') as "references",
             has_schema_privilege('public', 'parties', 'USAGE') as "public_usage", has_schema_privilege('evia_it_app', 'parties', 'CREATE') as "app_create"`.execute(
      admin(),
    );
    expect(rows[0]).toEqual({
      select: true,
      insert: true,
      update: true,
      delete: false,
      truncate: false,
      references: false,
      public_usage: false,
      app_create: false,
    });
  });
});

describe('migration 0014 — sites (EVM-021 AC1, AC2, AC3, AC5, AC6; ADR-0003; expand only)', () => {
  it('EVM-021 AC2 the table has the columns of the model — and no customer: a site is independent of the client (D7)', async () => {
    const { rows } = await sql<{ column_name: string }>`
      select column_name from information_schema.columns where table_schema = 'sites' and table_name = 'sites' order by ordinal_position`.execute(
      admin(),
    );
    expect(rows.map((row) => row.column_name)).toEqual([
      'id',
      'site_type',
      'street',
      'building_number',
      'apartment_number',
      'postal_code',
      'city',
      'parking_spot_number',
      'garage_level',
      'connection_power_kw',
      'metering_point_id',
      'distribution_system_operator_party_id',
      'manager_party_id',
      'notes',
      'search_text',
      'created_at',
      'created_by',
      'updated_at',
      'updated_by',
      'version',
      'deleted_at',
      'deleted_by',
    ]);
  });

  it('EVM-021 AC2 the id must be a UUIDv7 (CHECK) and is never generated by the database', async () => {
    await insertSite({ id: V7(501) });
    await fails(insertSite({ id: V7(501) }), '23505');
    await fails(insertSite({ id: '0198b0a0-0000-4000-8000-000000000502' }), '23514');
    const { rows } = await sql<{ column_default: string | null }>`
      select column_default from information_schema.columns where table_schema = 'sites' and column_name = 'id'`.execute(admin());
    expect(rows[0]?.column_default).toBeNull();
  });

  it('EVM-021 AC2 the type is one of four; the postal code is NN-NNN; lengths of the address are bounded', async () => {
    for (const siteType of ['single_family_house', 'multi_family_garage', 'commercial', 'other']) await insertSite({ siteType });
    await fails(insertSite({ siteType: 'garage' }), '23514');
    for (const postalCode of ['00001', '0-0001', '00-0011', 'ab-cde']) await fails(insertSite({ postalCode }), '23514');
    await insertSite({ street: 'S'.repeat(200), building: 'B'.repeat(20), apartment: 'A'.repeat(20), city: 'C'.repeat(100) });
    await fails(insertSite({ street: 'S'.repeat(201) }), '23514');
    await fails(insertSite({ building: 'B'.repeat(21) }), '23514');
    await fails(insertSite({ city: 'C'.repeat(101) }), '23514');
    await fails(insertSite({ street: '' }), '23514');
  });

  it('EVM-021 AC2 the parking spot and the level exist only for a garage in a multi-family building', async () => {
    await insertSite({ siteType: 'multi_family_garage', spot: '15', level: '-1' });
    await insertSite({ siteType: 'multi_family_garage', spot: '15' });
    await insertSite({ siteType: 'multi_family_garage' });
    for (const siteType of ['single_family_house', 'commercial', 'other']) {
      await fails(insertSite({ siteType, spot: '15' }), '23514');
      await fails(insertSite({ siteType, level: '-1' }), '23514');
    }
  });

  it('EVM-021 AC2 the connection power is in (0, 1000] kW with two decimals; the PPE at most 40 characters; notes 2000', async () => {
    for (const power of [0.01, 11, 1000]) await insertSite({ power });
    for (const power of [0, -1, 1000.01]) await fails(insertSite({ power }), '23514');
    await insertSite({ ppe: 'P'.repeat(40), notes: 'n'.repeat(2000) });
    await fails(insertSite({ ppe: 'P'.repeat(41) }), '23514');
    await fails(insertSite({ notes: 'n'.repeat(2001) }), '23514');
  });

  it('EVM-021 AC3 the OSD and the manager are foreign keys to parties without a cascade: an unknown party fails, a delete of a used party fails (RESTRICT)', async () => {
    await insertParty({ id: V7(700) });
    await insertParty({ id: V7(701), kind: 'property_manager' });
    await insertSite({ id: V7(702), osd: V7(700), manager: V7(701) });
    await fails(insertSite({ osd: V7(799) }), '23503');
    await fails(insertSite({ manager: V7(799) }), '23503');
    await fails(sql`delete from parties.parties where id = ${V7(700)}`.execute(admin()), '23001');
    await fails(sql`delete from parties.parties where id = ${V7(701)}`.execute(admin()), '23001');
    const { rows } = await sql<{ confdeltype: string }>`
      select confdeltype from pg_constraint where conrelid = 'sites.sites'::regclass and contype = 'f'`.execute(admin());
    expect(rows.map((row) => row.confdeltype)).toEqual(['r', 'r']);
  });

  it('EVM-021 AC1 the search text is generated from the address and the parking spot only: no PPE, no notes, accents removed', async () => {
    await insertSite({
      id: V7(800),
      street: 'ul. Łąkowa',
      building: '12A',
      apartment: '5',
      postalCode: '90-001',
      city: 'Łódź',
      siteType: 'multi_family_garage',
      spot: '15',
      level: '-1',
      ppe: 'PPE-SEKRET-1',
      notes: 'sekretna notatka',
    });
    await insertSite({ id: V7(801), street: 'ul. Testowa', building: '7', postalCode: '00-001', city: 'Warszawa' });
    const { rows } = await sql<{ id: string; search_text: string }>`
      select id, trim(regexp_replace(search_text, '\\s+', ' ', 'g')) as search_text from sites.sites where id in (${V7(800)}, ${V7(801)}) order by id`.execute(
      admin(),
    );
    expect(rows).toEqual([
      { id: V7(800), search_text: 'ul. lakowa 12a 5 90-001 lodz 15' },
      { id: V7(801), search_text: 'ul. testowa 7 00-001 warszawa' },
    ]);
  });

  it('EVM-021 AC1 the only index besides the key is a partial GIN trigram index on the search text (deleted_at is null)', async () => {
    const { rows } = await sql<{ indexname: string; indexdef: string }>`
      select indexname, indexdef from pg_indexes where schemaname = 'sites' order by indexname`.execute(admin());
    expect(rows.map((row) => row.indexname)).toEqual(['sites_pkey', 'sites_search_text_trgm_idx']);
    expect(rows[1]?.indexdef).toMatch(/USING gin \(search_text gin_trgm_ops\) WHERE \(deleted_at IS NULL\)/);
  });

  it('EVM-021 AC1 a search by 3 or more characters uses the trigram indexes of both tables (the planner is forced off the sequential scan: the tables are small)', async () => {
    const plan = await admin()
      .transaction()
      .execute(async (tx) => {
        await sql`set local enable_seqscan = off`.execute(tx);
        const plans: string[] = [];
        const sites = await sql<{ 'QUERY PLAN': string }>`
          explain select id from sites.sites
          where deleted_at is null and search_text ilike '%' || public.f_unaccent(lower(${'lodz'})) || '%' escape '\\'`.execute(tx);
        const parties = await sql<{ 'QUERY PLAN': string }>`
          explain select id from parties.parties
          where deleted_at is null and search_text ilike '%' || public.f_unaccent(lower(${'lodz'})) || '%' escape '\\'`.execute(tx);
        for (const { rows } of [sites, parties]) plans.push(rows.map((row) => row['QUERY PLAN']).join('\n'));
        return plans.join('\n');
      });
    expect(plan).toContain('sites_search_text_trgm_idx');
    expect(plan).toContain('parties_search_text_trgm_idx');
  });

  it('EVM-021 AC6 the application role may SELECT, INSERT and UPDATE sites but not DELETE, TRUNCATE or REFERENCES; PUBLIC has no access to the schema', async () => {
    const { rows } = await sql<Record<string, boolean>>`
      select has_table_privilege('evia_it_app', 'sites.sites', 'SELECT') as "select", has_table_privilege('evia_it_app', 'sites.sites', 'INSERT') as "insert",
             has_table_privilege('evia_it_app', 'sites.sites', 'UPDATE') as "update", has_table_privilege('evia_it_app', 'sites.sites', 'DELETE') as "delete",
             has_table_privilege('evia_it_app', 'sites.sites', 'TRUNCATE') as "truncate", has_table_privilege('evia_it_app', 'sites.sites', 'REFERENCES') as "references",
             has_schema_privilege('public', 'sites', 'USAGE') as "public_usage", has_schema_privilege('evia_it_app', 'sites', 'CREATE') as "app_create"`.execute(
      admin(),
    );
    expect(rows[0]).toEqual({
      select: true,
      insert: true,
      update: true,
      delete: false,
      truncate: false,
      references: false,
      public_usage: false,
      app_create: false,
    });
  });
});
