/**
 * Kysely types of the table the `sites` module owns (EVM-021). `platform` does not know module tables: the module narrows a handle
 * with `db.$extendTables<SiteTables>()`. The application role has SELECT, INSERT and UPDATE (no DELETE: soft delete only).
 * `search_text` is generated by the database — it can be read, never written. `connection_power_kw` is `numeric(6,2)`: the driver
 * returns it as a string and the representation turns it into a number.
 */
import type { ColumnType, Generated, GeneratedAlways, Kysely } from 'kysely';
import type { Database } from '../../../platform/database/database.ts';
import type { SiteType } from '../domain/site.ts';

export interface SitesTable {
  id: string;
  site_type: SiteType;
  street: string;
  building_number: string;
  apartment_number: string | null;
  postal_code: string;
  city: string;
  parking_spot_number: string | null;
  garage_level: string | null;
  connection_power_kw: ColumnType<string | null, number | null, number | null>;
  metering_point_id: string | null;
  distribution_system_operator_party_id: string | null;
  manager_party_id: string | null;
  notes: string | null;
  search_text: GeneratedAlways<string>;
  created_at: Date;
  created_by: string | null;
  updated_at: Date;
  updated_by: string | null;
  version: Generated<number>;
  deleted_at: Date | null;
  deleted_by: string | null;
}

export type SiteTables = { 'sites.sites': SitesTable };

export type SitesDb = Kysely<SiteTables>;

export const siteTables = (db: Kysely<Database>): SitesDb => db.$extendTables<SiteTables>();
